---

TileLayout:
  extension: petronia_portal
  enabled: true
  properties:
    default_window_behavior:
      - match:
          - key: executable
            match_type: glob
            value: "*firefox*"
        managed: true
        fit:
          justify_horizontal: left
          justify_vertical: top
          fit_horizontal: fit
          fit_vertical: fit
        initial_portal: default

    workspaces:
      # Layout 1: 1 screen.
      - name: 1 screen
        screens:
          - block:
              x: 0
              y: 0
              width: 1024
              height: 768
            layout:
              size: 1
              direction: horizontal
              contents:
              - type: portal
                value:
                  portal_aliases: ['default']
                  size: 2
                  preferred_location:
                    justify_horizontal: left
                    justify_vertical: top
                    fit_horizontal: shrink
                    fit_vertical: shrink
                  padding_top: 0
                  padding_bottom: 0
                  padding_left: 0
                  padding_right: 0
              - type: split
                value:
                  size: 1
                  direction: vertical
                  contents:
                    - type: portal
                      value:
                        portal_aliases: ['default']
                        size: 3
                        preferred_location:
                          justify_horizontal: right
                          justify_vertical: top
                          fit_horizontal: fit
                          fit_vertical: fit
                        padding_top: 0
                        padding_bottom: 0
                        padding_left: 0
                        padding_right: 0
                    - type: portal
                      value:
                        portal_aliases: ['default']
                        size: 2
                        preferred_location:
                          justify_horizontal: right
                          justify_vertical: bottom
                          fit_horizontal: shrink
                          fit_vertical: shrink
                        padding_top: 0
                        padding_bottom: 0
                        padding_left: 0
                        padding_right: 0

      # Layout 2: 2 screens, 1024x768 and 768x1024
      - name: 2 screens
        screens:
          - block:
              x: 0
              y: 0
              width: 1024
              height: 768
            layout:
              size: 1
              direction: horizontal
              contents:
              - type: portal
                value:
                  portal_aliases: ['default', '1-1']
                  size: 2
                  preferred_location:
                    justify_horizontal: left
                    justify_vertical: top
                    fit_horizontal: shrink
                    fit_vertical: shrink
                  padding_top: 0
                  padding_bottom: 0
                  padding_left: 0
                  padding_right: 0
              - type: split
                value:
                  size: 1
                  direction: vertical
                  contents:
                    - type: portal
                      value:
                        portal_aliases: ['1-2']
                        size: 3
                        preferred_location:
                          justify_horizontal: right
                          justify_vertical: top
                          fit_horizontal: fit
                          fit_vertical: fit
                        padding_top: 0
                        padding_bottom: 0
                        padding_left: 0
                        padding_right: 0
                    - type: portal
                      value:
                        portal_aliases: ['1-3']
                        size: 2
                        preferred_location:
                          justify_horizontal: right
                          justify_vertical: bottom
                          fit_horizontal: shrink
                          fit_vertical: shrink
                        padding_top: 0
                        padding_bottom: 0
                        padding_left: 0
                        padding_right: 0
          - block:
              x: 1024
              y: 0
              width: 768
              height: 1024
            layout:
              size: 1
              direction: vertical
              contents:
                - type: portal
                  value:
                    portal_aliases: ['2-1']
                    size: 1
                    preferred_location:
                      justify_horizontal: left
                      justify_vertical: top
                      fit_horizontal: shrink
                      fit_vertical: shrink
                    padding_top: 0
                    padding_bottom: 0
                    padding_left: 0
                    padding_right: 0
                - type: portal
                  value:
                    portal_aliases: ['2-2']
                    size: 3
                    preferred_location:
                      justify_horizontal: right
                      justify_vertical: top
                      fit_horizontal: fit
                      fit_vertical: fit
                    padding_top: 0
                    padding_bottom: 0
                    padding_left: 0
                    padding_right: 0
                - type: portal
                  value:
                    portal_aliases: ['2-3']
                    size: 2
                    preferred_location:
                      justify_horizontal: right
                      justify_vertical: bottom
                      fit_horizontal: shrink
                      fit_vertical: shrink
                    padding_top: 0
                    padding_bottom: 0
                    padding_left: 0
                    padding_right: 0
