
"""
Handlers for Windows VirtualKey (VK) codes and key names.
"""

from typing import Sequence, List, Dict, Set


def vk_to_names(vk: int) -> Sequence[str]:
    maps: List[str] = []
    for vk_str, code in STR_VK_MAP.items():
        # There are multiple mappings; return them all.
        if code == vk:
            maps.append(vk_str)
    if not maps:
        maps.append("#{0}".format(hex(vk)))
    return maps


def is_vk_modifier(vk: int) -> bool:
    return vk in _MODIFIER_KEYS


def is_specially_handled_vk_key(vk: int) -> bool:
    return vk in SPECIAL_MODIFIER_CHECK_VKEY_CODES


def contains_specially_handled_vk_key(vks: Sequence[int]) -> bool:
    for vk in vks:
        if vk in SPECIAL_MODIFIER_CHECK_VKEY_CODES:
            return True
    return False


# Built-in alias VK keys that represent several keys.
# Specific for modifiers.
VK_ALIASES: Dict[str, Sequence[str]] = {
    "win": ("lsuper", "rsuper",),
    "super": ("lsuper", "rsuper",),
    "shift": ("lshift", "rshift",),
    "control": ("lcontrol", "rcontrol",),
    "alt": ("lalt", "ralt",),
    "menu": ("lmenu", "rmenu",),
}


# Set of all recognized modifiers
MODIFIERS: Set[str] = {
    "shift",
    "lshift",
    "rshift",
    "control",
    "ctrl",
    "lcontrol",
    "lctrl",
    "rcontrol",
    "rctrl",
    "alt",
    "lalt",
    "ralt",
    "lsuper",
    "lwin",
    "rsuper",
    "rwin",
    "lmenu",
    "rmenu",
    "apps",
    "caps-lock",
}

# https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
STR_VK_MAP: Dict[str, int] = {
    "lmb": 0x01,                  # VK_LBUTTON  Left mouse button
    "rmb": 0x02,                  # VK_RBUTTON  Right mouse button
    "break": 0x03,                # VK_CANCEL   Control-break processing
    "mmb": 0x04,                  # VK_MBUTTON  Middle mouse button (three-button mouse)
    "x1mb": 0x05,                 # VK_XBUTTON1 X1 mouse button
    "x2mb": 0x06,                 # VK_XBUTTON2 X2 mouse button
    "x3mb": 0x07,                 # -           Undefined
    "back": 0x08,                 # VK_BACK     BACKSPACE key
    "backspace": 0x08,            # VK_BACK     BACKSPACE key
    "tab": 0x09,                  # VK_TAB      TAB key
    # - 0x0A-0B Reserved
    "clear": 0x0C,                # VK_CLEAR    CLEAR key
    "return": 0x0D,               # VK_RETURN   ENTER key
    "enter": 0x0D,                # VK_RETURN   ENTER key
    "cr": 0x0D,                   # VK_RETURN   ENTER key
    "lf": 0x0D,                   # VK_RETURN   ENTER key
    # - 0x0E-0F Undefined

    # These VK keys don't seem to get generated by the global key handler;
    # instead, the more low-level (lcontrol, rcontrol, etc) ones are.
    "shift": 0x10,                # VK_SHIFT    SHIFT key
    "sft": 0x10,                  # VK_SHIFT    SHIFT key
    "control": 0x11,              # VK_CONTROL  CTRL key
    "ctrl": 0x11,                 # VK_CONTROL  CTRL key
    "menu": 0x12,                 # VK_MENU     ALT key
    "alt": 0x12,                  # VK_MENU     ALT key

    "pause": 0x13,                # VK_PAUSE    PAUSE key
    "caps-lock": 0x14,            # VK_CAPITAL  CAPS LOCK key
    "kana": 0x15,                 # VK_KANA     IME Kana mode
    "hanguel": 0x15,              # VK_HANGUEL  IME Hanguel mode (maintained for compatibility; use VK_HANGUL)
    "hangul": 0x15,               # VK_HANGUL   IME Hangul mode
    # - 0x16 Undefined
    "junja": 0x17,                # VK_JUNJA    IME Junja mode
    "final": 0x18,                # VK_FINAL    IME final mode
    "hanja": 0x19,                # VK_HANJA    IME Hanja mode
    "kanji": 0x19,                # VK_KANJI    IME Kanji mode
    # 0x1A - Undefined
    "escape": 0x1B,               # VK_ESCAPE    ESC key
    "esc": 0x1B,                  # VK_ESCAPE    ESC key
    "convert": 0x1C,              # VK_CONVERT    IME convert
    "nonconvert": 0x1D,           # VK_NONCONVERT    IME nonconvert
    "accept": 0x1E,               # VK_ACCEPT    IME accept
    "modechange": 0x1F,           # VK_MODECHANGE    IME mode change request
    "space": 0x20,                # VK_SPACE    SPACEBAR
    "prior": 0x21,                # VK_PRIOR    PAGE UP key
    "pgup": 0x21,                 # VK_PRIOR    PAGE UP key
    "pageup": 0x21,               # VK_PRIOR    PAGE UP key
    "next": 0x22,                 # VK_NEXT    PAGE DOWN key
    "pgdn": 0x22,                 # VK_NEXT    PAGE DOWN key
    "pagedown": 0x22,             # VK_NEXT    PAGE DOWN key
    "end": 0x23,                  # VK_END    END key
    "home": 0x24,                 # VK_HOME    HOME key
    "left": 0x25,                 # VK_LEFT    LEFT ARROW key
    "up": 0x26,                   # VK_UP    UP ARROW key
    "right": 0x27,                # VK_RIGHT    RIGHT ARROW key
    "down": 0x28,                 # VK_DOWN    DOWN ARROW key
    "select": 0x29,               # VK_SELECT    SELECT key
    "print": 0x2A,                # VK_PRINT    PRINT key
    "execute": 0x2B,              # VK_EXECUTE    EXECUTE key
    "snapshot": 0x2C,             # VK_SNAPSHOT    PRINT SCREEN key
    "insert": 0x2D,               # VK_INSERT    INS key
    "delete": 0x2E,               # VK_DELETE    DEL key
    "del": 0x2E,                  # VK_DELETE    DEL key
    "help": 0x2F,                 # VK_HELP    HELP key
    "lsuper": 0x5B,               # VK_LWIN    Left Windows key (Natural keyboard)
    "lwin": 0x5B,                 # VK_LWIN    Left Windows key (Natural keyboard)
    "rsuper": 0x5C,               # VK_RWIN    Right Windows key (Natural keyboard)
    "rwin": 0x5C,                 # VK_RWIN    Right Windows key (Natural keyboard)
    "apps": 0x5D,                 # VK_APPS    Applications key (Natural keyboard)
    # 0x5E - Reserved
    "sleep": 0x5F,                # VK_SLEEP    Computer Sleep key
    "numpad0": 0x60,              # VK_NUMPAD0    Numeric keypad 0 key
    "numpad1": 0x61,              # VK_NUMPAD1    Numeric keypad 1 key
    "numpad2": 0x62,              # VK_NUMPAD2    Numeric keypad 2 key
    "numpad3": 0x63,              # VK_NUMPAD3    Numeric keypad 3 key
    "numpad4": 0x64,              # VK_NUMPAD4    Numeric keypad 4 key
    "numpad5": 0x65,              # VK_NUMPAD5    Numeric keypad 5 key
    "numpad6": 0x66,              # VK_NUMPAD6    Numeric keypad 6 key
    "numpad7": 0x67,              # VK_NUMPAD7    Numeric keypad 7 key
    "numpad8": 0x68,              # VK_NUMPAD8    Numeric keypad 8 key
    "numpad9": 0x69,              # VK_NUMPAD9    Numeric keypad 9 key
    "multiply": 0x6A,             # VK_MULTIPLY    Multiply key
    "add": 0x6B,                  # VK_ADD    Add key
    "separator": 0x6C,            # VK_SEPARATOR    Separator key
    "subtract": 0x6D,             # VK_SUBTRACT    Subtract key
    "decimal": 0x6E,              # VK_DECIMAL    Decimal key
    "divide": 0x6F,               # VK_DIVIDE    Divide key
    "f1": 0x70,                   # VK_F1    F1 key
    "f2": 0x71,                   # VK_F2    F2 key
    "f3": 0x72,                   # VK_F3    F3 key
    "f4": 0x73,                   # VK_F4    F4 key
    "f5": 0x74,                   # VK_F5    F5 key
    "f6": 0x75,                   # VK_F6    F6 key
    "f7": 0x76,                   # VK_F7    F7 key
    "f8": 0x77,                   # VK_F8    F8 key
    "f9": 0x78,                   # VK_F9    F9 key
    "f10": 0x79,                  # VK_F10    F10 key
    "f11": 0x7A,                  # VK_F11    F11 key
    "f12": 0x7B,                  # VK_F12    F12 key
    "f13": 0x7C,                  # VK_F13    F13 key
    "f14": 0x7D,                  # VK_F14    F14 key
    "f15": 0x7E,                  # VK_F15    F15 key
    "f16": 0x7F,                  # VK_F16    F16 key
    "f17": 0x80,                  # VK_F17    F17 key
    "f18": 0x81,                  # VK_F18    F18 key
    "f19": 0x82,                  # VK_F19    F19 key
    "f20": 0x83,                  # VK_F20    F20 key
    "f21": 0x84,                  # VK_F21    F21 key
    "f22": 0x85,                  # VK_F22    F22 key
    "f23": 0x86,                  # VK_F23    F23 key
    "f24": 0x87,                  # VK_F24    F24 key
    # 0x88-8F - Unassigned
    "numlock": 0x90,              # VK_NUMLOCK    NUM LOCK key
    "scroll": 0x91,               # VK_SCROLL    SCROLL LOCK key
    # 0x92-96 - OEM specific
    # 0x97-9F - Unassigned
    "lshift": 0xA0,               # VK_LSHIFT    Left SHIFT key
    "rshift": 0xA1,               # VK_RSHIFT    Right SHIFT key
    "lcontrol": 0xA2,             # VK_LCONTROL    Left CONTROL key
    "lctrl": 0xA2,             # VK_LCONTROL    Left CONTROL key
    "rcontrol": 0xA3,             # VK_RCONTROL    Right CONTROL key
    "rctrl": 0xA3,             # VK_RCONTROL    Right CONTROL key
    "lmenu": 0xA4,                # VK_LMENU    Left MENU key
    "lalt": 0xA4,                # VK_LMENU    Left MENU key
    "rmenu": 0xA5,                # VK_RMENU    Right MENU key
    "ralt": 0xA5,                # VK_RMENU    Right MENU key
    "browser-back": 0xA6,         # VK_BROWSER_BACK    Browser Back key
    "browser-forward": 0xA7,      # VK_BROWSER_FORWARD    Browser Forward key
    "browser-refresh": 0xA8,      # VK_BROWSER_REFRESH    Browser Refresh key
    "browser-stop": 0xA9,         # VK_BROWSER_STOP    Browser Stop key
    "browser-search": 0xAA,       # VK_BROWSER_SEARCH    Browser Search key
    "browser-favorites": 0xAB,    # VK_BROWSER_FAVORITES    Browser Favorites key
    "browser-home": 0xAC,         # VK_BROWSER_HOME    Browser Start and Home key
    "volume-mute": 0xAD,          # VK_VOLUME_MUTE    Volume Mute key
    "volume-down": 0xAE,          # VK_VOLUME_DOWN    Volume Down key
    "volume-up": 0xAF,            # VK_VOLUME_UP    Volume Up key
    "media-next-track": 0xB0,     # VK_MEDIA_NEXT_TRACK    Next Track key
    "media-prev-track": 0xB1,     # VK_MEDIA_PREV_TRACK    Previous Track key
    "media-stop": 0xB2,           # VK_MEDIA_STOP    Stop Media key
    "media-play-pause": 0xB3,     # VK_MEDIA_PLAY_PAUSE    Play/Pause Media key
    "launch-mail": 0xB4,          # VK_LAUNCH_MAIL    Start Mail key
    "launch-media-select": 0xB5,  # VK_LAUNCH_MEDIA_SELECT    Select Media key
    "launch-app1": 0xB6,          # VK_LAUNCH_APP1    Start Application 1 key
    "launch-app2": 0xB7,          # VK_LAUNCH_APP2    Start Application 2 key
    # 0xB8-B9 - Reserved

    "oem_1": 0xBA,                # VK_OEM_1    Used for miscellaneous characters;
                                  # it can vary by keyboard.  For the US standard keyboard, the ';:' key
    ":": 0xBA,
    ";": 0xBA,
    "colon": 0xBA,
    "semi-colon": 0xBA,

    "oem_plus": 0xBB,             # VK_OEM_PLUS    For any country/region, the '+=' key
    "plus": 0xBB,
    "=": 0xBB,
    "equal": 0xBB,

    "oem_comma": 0xBC,            # VK_OEM_COMMA    For any country/region, the ',<' key
    "comma": 0xBC,
    ",": 0xBC,
    "<": 0xBC,
    "less-than": 0xBC,

    "oem_minus": 0xBD,            # VK_OEM_MINUS    For any country/region, the '-_' key
    "minus": 0xBD,
    "dash": 0xBD,
    "under": 0xBD,
    "lodash": 0xBD,

    "oem_period": 0xBE,           # VK_OEM_PERIOD    For any country/region, the '.>' key
    ".": 0xBE,
    "period": 0xBE,
    ">": 0xBE,
    "greater-than": 0xBE,

    "oem_2": 0xBF,                # VK_OEM_2    Used for miscellaneous characters;
                                  # it can vary by keyboard.  For the US standard keyboard, the '/?' key
    "/": 0xBF,
    "slash": 0xBF,
    "?": 0xBF,
    "question": 0xBF,
    "question-mark": 0xBF,
    "oem2": 0xBF,

    "oem_3": 0xC0,                # VK_OEM_3    Used for miscellaneous characters;
                                  # it can vary by keyboard.  For the US standard keyboard, the '`~' key
    "oem3": 0xC0,
    "~": 0xC0,
    "tilde": 0xC0,
    "`": 0xC0,
    "back-tick": 0xC0,
    # 0xC1-D7 - Reserved
    # 0xD8-DA - Unassigned

    "oem_4": 0xDB,                # VK_OEM_4    Used for miscellaneous characters;
                                  # it can vary by keyboard.  For the US standard keyboard, the '[{' key
    "oem4": 0xDB,
    "[": 0xDB,
    "left-bracket": 0xBD,
    "left-brace": 0xBD,
    "open-bracket": 0xBD,
    "open-brace": 0xBD,
    "{": 0xDB,
    "left-curly-bracket": 0xDB,
    "left-curly-brace": 0xDB,
    "open-curly-bracket": 0xDB,
    "open-curly-brace": 0xDB,

    "oem_5": 0xDC,                # VK_OEM_5    Used for miscellaneous characters;
                                  # it can vary by keyboard.  For the US standard keyboard, the '\|' key
    "oem5": 0xDC,
    "|": 0xDC,
    "\\": 0xDC,
    "pipe": 0xDC,
    "backslash": 0xDC,

    "oem_6": 0xDD,                # VK_OEM_6    Used for miscellaneous characters;
                                  # it can vary by keyboard.  For the US standard keyboard, the ']}' key
    "oem6": 0xDD,
    "]": 0xDD,
    "}": 0xDD,
    "right-bracket": 0xDD,
    "right-brace": 0xDD,
    "close-bracket": 0xDD,
    "close-brace": 0xDD,
    "closed-bracket": 0xDD,
    "closed-brace": 0xDD,
    "right-curly-bracket": 0xDD,
    "right-curly-brace": 0xDD,
    "close-curly-bracket": 0xDD,
    "close-curly-brace": 0xDD,
    "closed-curly-bracket": 0xDD,
    "closed-curly-brace": 0xDD,

    "oem_7": 0xDE,                # VK_OEM_7    Used for miscellaneous characters;
                                  # it can vary by keyboard.  For the US standard keyboard,
                                  # the 'single-quote/double-quote' key
    "oem7": 0xDE,
    '"': 0xDE,
    "'": 0xDE,
    "quote": 0xDE,
    "tick": 0xDE,
    "double-quote": 0xDE,

    "oem_8": 0xDF,                # VK_OEM_8    Used for miscellaneous characters; it can vary by keyboard.
    "oem8": 0xDF,
    # 0xE0 - Reserved
    # 0xE1 - OEM specific

    "oem_102": 0xE2,              # VK_OEM_102    Either the angle bracket key or the backslash key on
                                  # the RT 102-key keyboard
    "oem102": 0xE2,
    # 0xE3-E4 - OEM specific
    "processkey": 0xE5,           # VK_PROCESSKEY    IME PROCESS key
    # 0xE6 - OEM specific
    "packet": 0xE7,               # VK_PACKET    Used to pass Unicode characters as if they were
                                  # keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual
                                  # Key value used for non-keyboard input methods. For more
                                  # information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP
    # 0xE8 - Unassigned
    # 0xE9-F5 - OEM specific
    "attn": 0xF6,                 # VK_ATTN    Attn key
    "crsel": 0xF7,                # VK_CRSEL    CrSel key
    "exsel": 0xF8,                # VK_EXSEL    ExSel key
    "ereof": 0xF9,                # VK_EREOF    Erase EOF key
    "play": 0xFA,                 # VK_PLAY    Play key
    "zoom": 0xFB,                 # VK_ZOOM    Zoom key
    "noname": 0xFC,               # VK_NONAME    Reserved
    "pa1": 0xFD,                  # VK_PA1    PA1 key
    "oem_clear": 0xFE,            # VK_OEM_CLEAR    Clear key
    # 0x3A-40 - Undefined
    "0": 0x30,                    # 0 key
    "1": 0x31,                    # 1 key
    "2": 0x32,                    # 2 key
    "3": 0x33,                    # 3 key
    "4": 0x34,                    # 4 key
    "5": 0x35,                    # 5 key
    "6": 0x36,                    # 6 key
    "7": 0x37,                    # 7 key
    "8": 0x38,                    # 8 key
    "9": 0x39,                    # 9 key
    "a": 0x41,                    # A key
    "b": 0x42,                    # B key
    "c": 0x43,                    # C key
    "d": 0x44,                    # D key
    "e": 0x45,                    # E key
    "f": 0x46,                    # F key
    "g": 0x47,                    # G key
    "h": 0x48,                    # H key
    "i": 0x49,                    # I key
    "j": 0x4A,                    # J key
    "k": 0x4B,                    # K key
    "l": 0x4C,                    # L key
    "m": 0x4D,                    # M key
    "n": 0x4E,                    # N key
    "o": 0x4F,                    # O key
    "p": 0x50,                    # P key
    "q": 0x51,                    # Q key
    "r": 0x52,                    # R key
    "s": 0x53,                    # S key
    "t": 0x54,                    # T key
    "u": 0x55,                    # U key
    "v": 0x56,                    # V key
    "w": 0x57,                    # W key
    "x": 0x58,                    # X key
    "y": 0x59,                    # Y key
    "z": 0x5A,                    # Z key
}

_MODIFIER_KEYS: Set[int] = set()
for __k in MODIFIERS:
    _MODIFIER_KEYS.add(STR_VK_MAP[__k])


SPECIAL_MODIFIER_CHECK_VKEY_CODES = (
    STR_VK_MAP['lsuper'], STR_VK_MAP['rsuper']
)
