---

name: petronia.core.protocol.configuration
type: protocol
version: [1, 0, 0]
about: Conventions and events for accessing, storing, and setting per-extension configuration.
description: >
  A common API plus naming conventions for handling configuration settings on all extensions.

  As a common API, all extensions, including stand-alone ones, can implement it to allow for
  configuration publication and updates.

  This prototype explicitly declares the APIs involved, but there are additional conventions
  that should be followed.  The current configuration data should be stored in the datastore
  extension under the target name `(extension):configuration`.  The structure of the configuration
  should to be defined in the "state-data" section.  The configuration structure, as a json object,
  should be uploaded to the datastore at extension start time in the target name
  `(extension):configuration-metadata`.

licenses:
  - MIT
authors:
  - Petronia Project


events:
  "set-configuration:request":
    description: >
      Uploads the configuration data to the implementing extension.

      The configuration data should be defined by an extension in the "state-data" section
      of the extension's metadata definition file, with the name "configuration" and unique target
      ID "configuration".

    priority: io
    send-access: public
    receive-access: public
    fields:
      request_id:
        type: reference
        ref: response-identifier

  "set-configuration:success":
    description: >
      Reports that the configuration update request succeeded.

      Will be sent to the sender ID that sent the original request.

    priority: normal
    send-access: public
    receive-access: public
    fields:
      request_id:
        type: reference
        ref: response-identifier

  "set-configuration:failure":
    description: >
      Reports that the configuration update request failed.

      Will be sent to the sender ID that sent the original request.

    priority: normal
    send-access: public
    receive-access: public
    fields:
      request_id:
        type: reference
        ref: response-identifier
      error:
        type: reference
        ref: error


references:
  # =========================================================================
  # Standard Types
  response-identifier:
    description: >
      An identifier, created by the sender, that is included in the response so the sender matches the
      response to the sent message.  Combined with the sender's ID (for requests) or target's ID
      (for responses) creates a unique identifier.
    type: int
    min-value: -999999
    max-value: 9999999
  localizable-message:
    description: A localizable message for user display.
    type: structure
    fields:
      catalog:
        description: >
          The name of the translation file, or "domain", that contains
          the translations.
        type: string
        min-length: 2
        max-length: 300
      message:
        description: >
          The message ID to look up in the catalog.  If the message
          has no translation, this is directly displayed to the user.
        type: string
        min-length: 1
        max-length: 10000
      arguments:
        description: >
          List of arguments to be inserted into the translated message.
          Each argument should have a distinct name from all the other
          arguments in this message; the name is how the message references
          the arguments.
        type: array
        min-length: 0
        max-length: 100
        optional: true
        value-type:
          type: reference
          ref: message-argument
  message-argument:
    description: An argument to be inserted into the localizable message.
    type: structure
    fields:
      name:
        description: Name of the arugment, referenced by the message.
        type: string
        min-length: 1
        max-length: 50
      value:
        description: Value of the argument.  It must be a simple type.
        type: reference
        ref: message-argument-value
  message-argument-value:
    description: A replacement value for a named argument in the message.
    type: selector
    type-mapping:
      string:
        type: string
        min-length: 0
        max-length: 10000
      int:
        type: int
      float:
        type: float
      bool:
        type: bool
      datetime:
        type: datetime
      string_list:
        type: array
        min-length: 0
        max-length: 100
        value-type:
          type: string
          min-length: 0
          max-length: 10000
      int_list:
        type: array
        min-length: 0
        max-length: 100
        value-type:
          type: int
      float_list:
        type: array
        min-length: 0
        max-length: 100
        value-type:
          type: float
      bool_list:
        type: array
        min-length: 0
        max-length: 100
        value-type:
          type: bool
      datetime_list:
        type: array
        min-length: 0
        max-length: 100
        value-type:
          type: datetime
  error:
    type: structure
    description: A description of a failure.
    fields:
      identifier:
        description: >
          The identifier that uniquely defines this error.  Useful for
          automation that needs to perform operations based on specific
          error messages.
        type: string
        min-length: 5
        max-length: 600
      categories:
        description: >
          A collection of general categories that define the error.
          Useful for automation that can act differently depending on
          the contents.
        type: array
        min-length: 1
        max-length: 100
        value-type:
          description: General error category.
          type: enum
          values:
            - file
            - os
            - configuration
            - network
            - access-restriction
            - invalid-user-action
            - internal
      source:
        description: The source of the error, if known.
        type: string
        min-length: 2
        max-length: 300
        optional: true
      messages:
        description: The localizable messages associated with this error.
        type: array
        min-length: 1
        max-length: 100
        value-type:
            type: reference
            ref: localizable-message
