---

# Extensions that the system defines to load.

Timer:
  extension: petronia_core.timer
  enabled: true
  properties:
    interval_seconds: 1.2

Datastore:
  extension: petronia_core.datastore
  enabled: true

Platform:
  extension: petronia_native_windows
  enabled: true
  properties:
    hotkeys:
      own_super_key: False
    virtual_screens:
      mapped_screens_by_monitors: []
