---

startup:
  extensions:
    - petronia_core.datastore
    - petronia_native_windows
    - petronia_core.timer
  extension-dirs:
    - ${SYS_PATH}
    # - ${DATA_DIR}/core-extensions
    # - ${DATA_DIR}/native-handler
