
"""Common constants for the event stream."""

BINARY_PACKET_MARKER_1 = b'\0'
BINARY_PACKET_MARKER_1_INT = 0
BINARY_PACKET_MARKER_2 = b'\0'
BINARY_PACKET_MARKER_2_INT = 0
BINARY_PACKET_MARKER_3 = b'['
BINARY_PACKET_MARKER_3_INT = ord('[')
BINARY_EVENT_ID_MARKER = b'e'
BINARY_EVENT_ID_MARKER_INT = ord('e')
BINARY_SOURCE_ID_MARKER = b's'
BINARY_SOURCE_ID_MARKER_INT = ord('s')
BINARY_TARGET_ID_MARKER = b't'
BINARY_TARGET_ID_MARKER_INT = ord('t')
BINARY_JSON_CONTENTS_MARKER = b'{'
BINARY_JSON_CONTENTS_MARKER_INT = ord('{')
BINARY_BLOB_CONTENTS_MARKER = b'['
BINARY_BLOB_CONTENTS_MARKER_INT = ord('[')
EMPTY_BINARY = b''

MAX_ID_SIZE = 2047
MIN_ID_SIZE = 1
MAX_JSON_SIZE = 65535
MIN_JSON_SIZE = 2
MAX_BLOB_SIZE = 10485760
MIN_BLOB_SIZE = 0

BROADCAST_EVENT_TARGET_ID = '*'
