
"""
Basic events generated by layouts.
"""

from .bootstrap import bootstrap_layout_api as start_extension
from .bootstrap import EXTENSION_METADATA

from .events import (
    TARGET_ID_LAYOUT,
    EVENT_ID_LAYOUT_CHANGED,
    LayoutChangedEvent,
    as_layout_changed_listener,
    send_layout_changed_event,

    EVENT_ID_REQUEST_MOVE_RESIZE_FOCUSED_WINDOW,
    RequestMoveResizeFocusedWindowEvent,
    as_request_move_resize_focused_window_listener,
    send_request_move_resize_focused_window_event,

    EVENT_ID_REQUEST_SHIFT_LAYOUT_FOCUS,
    RequestShiftLayoutFocusEvent,
    as_request_shift_layout_focus_listener,
    send_request_shift_layout_focus_event,

    EVENT_ID_REQUEST_SET_FOCUSED_WINDOW_VISIBILITY,
    RequestSetFocusedWindowVisibilityEvent,
    as_request_set_focused_window_visibility_listener,
    send_request_set_window_visibility_event,
)
