---

Logger:
  extension: default.logging.file
  enabled: true
  properties:
    filename: petronia.log
    # filename: "-"
    format: "%H:%M:%S [{LEVEL}] {src:16s}: {msg}"
    default: warn
    category-levels:
      - cat: "petronia.base."
        level: trace
      - cat: "petronia.boot."
        level: trace
      - cat: "petronia.defimpl.layout."
        level: debug
      - cat: "petronia.defimpl.platform."
        level: debug
      - cat: "petronia.defimpl.shutdown."
        level: trace
